[project]
name = "test2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "heonjiK", email = "hanzzi@g.skku.edu" }
]
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "feedparser>=6.0.14",
    "requests>=2.34.2",
]

[project.scripts]
test2 = "test2:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
